config/routes.rb
DbcOverflow::Application.routes.draw do

  resources :posts do 
    resources :comments
  end

  root :to => "posts#index"

  resources :sessions, :only => [:new, :destroy, :create]

  resources :users

  resources :votes, :only => [:create, :update]

  match "/signup", to: "users#new"

  match "/logout", to: "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	attr_accessible :content
	has_many :votes, :as => :votable
	
	validates :content, presence: true

	def total_votes
    # post = Post.find(post_id)
    return 0 if votes.empty?
    votes.inject(0) { |sum, vote| sum + vote.value}
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes, :as => :votable
  
  attr_accessible :title, :image_url

  validates :title, :image_url, presence: true

  def total_votes
    # post = Post.find(post_id)
    return 0 if votes.empty?
    votes.inject(0) { |sum, vote| sum + vote.value}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, :polymorphic => true
  belongs_to :user

  # makes sure a user can only vote once per comment or post
  validates_uniqueness_of :user_id, scope: [:votable_id, :votable_type]
  validates :votable_type, format: {with: /Post|Comment/}

  attr_accessible :votable_id, :user_id, :votable_type, :value

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery #what does this do?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  helper_method :current_user #make available for views!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
      @comment = Comment.create(params[:comment])
      User.find(current_user.id).comments << @comment     #XXXXXXXXXXXXXX INSERT SESSION KEY
      Post.find(params[:post_id]).comments << @comment
      redirect_to :back
  end

  def edit
    puts params[:id]
    if current_user && current_user.id == Comment.find(params[:id]).user.id
      @comment = Comment.find(params[:id])
      @post = Post.find(params[:post_id])
    else
      render text: "gtfo"
    end
  end

  def update
    comment = Comment.find(params[:id])
    comment.update_attributes(params[:comment])
    redirect_to post_path(comment.post)
  end

  def destroy
    Comment.destroy(params[:id])
    redirect_to root_path
  end

  def show
    puts params.inspect
    comment = Comment.find(params[:id])
    render text: comment
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 4).order("id DESC")
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(params[:post])
    User.find(current_user.id).posts << post #XXXXXXXXXXXXXX what is the session symbol
    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def edit
    if current_user && current_user.id == Post.find(params[:id]).user.id
      @post = Post.find(params[:id]) 
    else
      render text: "gtfo"
    end
    
  end

  def update
    Post.find(params[:id]).update_attributes(params[:post])
    redirect_to root_path
  end

  def destroy
    post = Post.destroy(params[:id])
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    user = user.try(:authenticate, params[:session][:password])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      #kick back to signin page
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      #kick back to signup page
      render :new
    end
  end

  def show
    redirect_to root_path if !current_user || User.find(params[:id]) != current_user
    @posts = current_user.posts
    @comments = current_user.comments
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = Vote.find_or_create_by_user_id_and_votable_id_and_votable_type(votable_type: params[:votable_type],
                votable_id: params[:votable_id],
                user_id: current_user.id)
    vote.update_attributes(value: params[:vote_value])

    post = params[:votable_type].classify.constantize.find(params[:votable_id])


    vote.save
    render :json => {vote_count: post.total_votes, post_id: params[:votable_id]}.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li>
  	<span style="font-weight: 600;"id="votecount-<%=comment.id%>"><%= comment.total_votes %></span>
    "<%= comment.content %>" - <%= comment.user.name %>
    <% if current_user != nil && comment.user.id == current_user.id%>
    <%= link_to votes_path(votable_id: comment.id, votable_type: comment.class, vote_value: 1), :remote=>true, :method=> 'post', :class => "vote" do %>
         <img class="commentarrow" src="http://cdn1.iconfinder.com/data/icons/large-black-icons/512/Up_arrow_vote_like_upload.png">
      <% end %>
       
      <%= link_to votes_path(votable_id: comment.id, votable_type: comment.class, vote_value: -1), :remote=>true, :method=> 'post', :class => "vote" do %>
         <img class="commentarrow" src="http://www.3h.ca/blog/wp-content/uploads/2013/01/downvote-copy.png">
      <% end %>
      <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
    <% end %>
  </li>
</ul>

app/views/comments/_new_comment.html.erb
<%= form_for(comment) do |f| %>
  sfljabf
  <% end %>

app/views/comments/edit.html.erb
<%= form_for [@post, @comment] do |f|%>
  <%= f.text_field :content %>
  <%= f.submit "Submit changes" %>
<% end %>

<%= link_to "Delete", post_comment_path(@comment), :method => :delete %>

app/views/comments/new.html.erb
<%= render "new_comment", :locals => {comment: @comment} %>

app/views/layouts/_nav.html.erb
<nav>
  <span class="brand">
    <%= link_to "GIFBROVERFLOW", root_path %>
  </span>
  <span class="menu">
    <%= link_to "Sign Up", signup_path if current_user.nil? %>
    <%= link_to "Sign In", new_session_path if current_user.nil? %>
    <%= link_to "Brofile", user_path(current_user) if current_user %>
    <%= link_to "Log Out", logout_path if current_user %>

  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMGOverflow</title>
  <link href='http://fonts.googleapis.com/css?family=Quantico|Advent+Pro' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="main_container">
    <%= render 'layouts/nav' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/edit.html.erb
<div class="post_form">
  <%= form_for @post do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :image_url %>
    <%= f.submit "Submit Changes" %>
  <% end %>
</div>

<%= link_to "Delete", post_path(@post), :method => :delete %>

app/views/posts/index.html.erb
<h1>BROPOSITORY</h1>

<div class="post_list">
  <% @posts.each do |post| %>
    <div class="post">
      <%= image_tag post.image_url %>
      <p><%= link_to post.title, post_path(post) %></p>
     
      <%= link_to votes_path(votable_id: post.id, votable_type: post.class, vote_value: 1), :remote=>true, :method=> 'post', :class => "vote" do %>
         <img class="arrow" src="http://cdn1.iconfinder.com/data/icons/large-black-icons/512/Up_arrow_vote_like_upload.png">
      <% end %>
       <div id="votecount-<%=post.id%>"><%= post.total_votes %></div>
      <%= link_to votes_path(votable_id: post.id, votable_type: post.class, vote_value: -1), :remote=>true, :method=> 'post', :class => "vote" do %>
         <img class="arrow" src="http://www.3h.ca/blog/wp-content/uploads/2013/01/downvote-copy.png">
      <% end %>

    </div>
  <% end %>

</div>

  <%= will_paginate @posts %>

app/views/posts/new.html.erb
<h2>Make a New Post</h2>

<div class="post_form">
  <%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="post_full">  
  <img src="<%=  @post.image_url %>"/>
</div>
<% if current_user %>
  <div class = "comment_form">
    <%= form_for [@post, @comment]  do |f| %>
      <%= f.label :comment  %>
      <%= f.text_field :content %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
<% else %>
  <%= link_to "Please Login to comment", new_session_path %>
<% end %>

<%= render @comments %>

app/views/users/new.html.erb
<link rel="stylesheet" type="text/css" href="mystyle.css">
<div class="myform" id="stylized">
    <div class="login_signup_form">
      <%= form_for @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %> <br/>

        <%= f.label :email %>
        <%= f.text_field :email %> <br/>

        <%= f.label :password %>
        <%= f.password_field :password %> <br/>

        <%= f.label :confirm_email %>
        <%= f.password_field :password_confirmation %> <br/>

        <button type="submit">Sign-up</button>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h2> Welcome to your profile </h2>

<%= link_to "New", new_post_path %> </br>

<h3> Your Posts: </h3>
<div class="post_list">
  <% @posts.each do |post| %>
    <h5><%= post.title %></h5>
    <img src='<%=  post.image_url %>'/>
    <%= link_to "Edit", edit_post_path(post) %>
  <% end %>
</div>

<h3> Your Comments </h3>
<div class ="comment_list">
  <% @comments.each do |comment| %>
    <p><strong><%= comment.content %></strong></br> 
    on: <%= link_to comment.post.title, post_path(comment.post) %></p>
  <% end %>
</div>
<% 